defaults:
  - hydra: experiment
  - _self_

name: simple_grid
num_tasks: 250
num_episodes: 1e4
world_params:
  _target_: rlg.experiments.simple_grid.WorldParams
  slip_dist:
    _target_: rlg.np_utils.gaussian_mixture.GaussianMixture
    weights: [0.8, 0.2]
    means: [0.03, 0.1]
    stds: [0.01, 0.01]
  width: 6
bounds:
  gamma: 2
  eta: 1e-2
  step_size: 5
  n_jobs: 8
