defaults:
  - hydra: simple
  - _self_

name: deep_ltl
run: main

env:
  name: ZoneEnv
  use_precomputed_resets: true
  precomputed_resets_path: sampled_resets_test.eqx

task_sampling:
  depth: [1, 3]
  reach: [1, 2]
  avoid: [0, 3]

eval:
  num_tasks: 1000
  num_episodes_per_task: 10000
  deterministic: false
  task_batch_size: 50 # number of tasks to process in parallel during evaluation
  episode_batch_size: 500 # number of episodes to process in parallel per task during evaluation

# Output settings
output:
  dir: ../${env.name}/eval/${run}
  results_file: episode_returns.parquet
  tasks_file: task_params.parquet

model:
  _target_: jaxltl.deep_ltl.model.deep_ltl.DeepLTLModel
  _recursive_: false
  env_net:
    _target_: jaxltl.networks.mlp.MLP
    hidden_sizes: [128]
    out_size: 64
    activation: ${act:tanh}
  actor:
    _target_: jaxltl.deep_ltl.model.actor.continuous_actor.ContinuousActor
    hidden_sizes: [64, 64, 64]
    hidden_activation: ${act:relu}
    output_activation: ${act:tanh}
    state_dependent_std: true
  critic:
    _target_: jaxltl.networks.mlp.MLP
    hidden_sizes: [64, 64]
    activation: ${act:tanh}
  sequence:
    embedding_dim: 16
    deep_sets:
      _target_: jaxltl.networks.deep_sets.DeepSets
      hidden_sizes: [32]
      out_size: 16
      activation: ${act:relu}
