defaults:
  - hydra: experiment
  - _self_

name: eval_cheetah

# Environment settings
env:
  episode_length: 1000

# Task sampling settings (log-uniform distribution)
task_sampling:
  log_tau_min: -1.0
  log_tau_max: 1.0

# Checkpoint settings
checkpoint:
  path: ../cheetah/cheetah_ckp # Path to checkpoint directory. If null, uses latest from experiments/cheetah/cheetah_ckp

# Evaluation settings
eval:
  num_tasks: 1000
  num_episodes_per_task: 10000
  deterministic: true
  # Batch sizes for memory efficiency
  # task_batch_size: 10 # Number of tasks to evaluate in parallel
  # episode_batch_size: 500 # Number of episodes per task in a single batch

# Output settings
output:
  dir: .
  results_file: episode_returns.parquet
  tasks_file: task_params.parquet

# Random seed
seed: 0

batch_size: 8192
