defaults:
  - hydra: simple
  - _self_

env:
  name: cheetah # cheetah or walker
  episode_length: 1000

task_sampling:
  log_tau_min: -1.0
  log_tau_max: 1.0

checkpoint_path: models/${env.name}/

# Evaluation settings
eval:
  num_tasks: 10
  num_episodes_per_task: 10
  deterministic: true

batch_size: 8192 # Number of episodes to evaluate in parallel

# Output settings
output:
  dir: data/${env.name}/
  results_file: episode_returns.parquet
  tasks_file: task_params.parquet

# Random seed
seed: 0
